version: '3.8'
services:
  db:
    image: 'postgres:latest'
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    command: [ "redis-server", "--bind", "redis", "--port", "6379" ]
    volumes:
      - 'redis:/data'

  rails:
    build: ./
    ports:
      - '3000:3000'
    volumes:
      - .:/chatapp
    depends_on:
      - db
      - redis
    environment:
      - RAILS_MASTER_KEY=25b8d8fafd06af4dfc4c0134c9b46c71
      - DATABASE_HOST=db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=root

volumes:
  postgres:
  redis:
