name: Chat APP CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: chatroom_test_test
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.0

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Assets precompile
      run: |
        SECRET_KEY_BASE_DUMMY=1 bundle exec rails assets:precompile

    - name: Run linter
      run: bundle exec standardrb

    - name: Run tests
      run: bundle exec rspec
